os: linux
dist: trusty

services: docker

language: shell

branches:
  only:
    - master

before_install:
  - env | sort
  - export DOCKER_REPO="monogramm/docker-ngxp"
  - export IMAGE_NAME="${DOCKER_REPO}:${VARIANT}-travis"
  - export name="ngxp"
  - export home=$(pwd)
  - export travis_dir="${home}/images/${VARIANT}"

install:
  # Test container build
  - travis_wait 120 docker build -t "${IMAGE_NAME}" "$travis_dir"

before_script:
  - docker images

script:
  # Test container run
  - docker run --name "${name}" -d "${IMAGE_NAME}"
  - docker ps
  - docker logs "${name}"

notifications:
  email: false

jobs:
  allow_failures:
    - env: VARIANT=11-jdk-slim

env: # Environments
    - VARIANT=11-jdk-slim
    - VARIANT=8-jdk-alpine
    - VARIANT=8-jdk-slim
