dist: trusty
sudo: required

services: docker

language: bash

branches:
  only:
    - master

before_script:
  - env | sort
  - name="ngxp"
  - image="monogramm/docker-ngxp:${VARIANT}_travis"
  - dir="images/${VARIANT}"

script:
  - travis_wait 50 docker build -t "$image" "$dir"

after_script:
  - docker images
  - docker run --name "$name" "$image"
  - docker ps
  - docker logs "$name"

notifications:
  email: false

env: # Environments
    - VARIANT=alpine
    - VARIANT=jdk
