os: linux
dist: trusty

services: docker

language: shell

branches:
  only:
    - master

before_install:
  - env | sort
  - export DOCKER_REPO="monogramm/docker-ngxp"
  - export IMAGE_NAME="${DOCKER_REPO}:${VARIANT}_travis"
  - export home=$(pwd)
  - export travis_dir="${home}/images/${VARIANT}"

install:
  # Test container build
  - travis_wait 50 docker build -t "${IMAGE_NAME}" "$travis_dir"

before_script:
  - docker images

script:
  # Test container run
  - docker run --name "${DOCKER_REPO}" -d "${IMAGE_NAME}"
  - docker ps
  - docker logs "${DOCKER_REPO}"
  - docker exec -d "${IMAGE_NAME}" java -version
  - docker exec -d "${IMAGE_NAME}" sdkmanager --list
  - docker exec -d "${IMAGE_NAME}" node --version
  - docker exec -d "${IMAGE_NAME}" npm --version
  - docker exec -d "${IMAGE_NAME}" ng --version
  - docker exec -d "${IMAGE_NAME}" tns info

notifications:
  email: false

jobs:
  allow_failures:
    - env: VARIANT=11-jdk-slim

env: # Environments
    - VARIANT=11-jdk-slim
    - VARIANT=8-jdk-alpine
    - VARIANT=8-jdk-slim
